### ISSUE TITLE
Window error while open Burpsuite (Bug)

### ISSUE THREAD

**Issue by bountyhacking** [r1vs3c/auto-bspwm#1]
When i started burpsuite to make some labs on portswigger, thw window manager it does not work propertly. I tried to restart Bspwn with `Win + Alt + R` and it didnt worked. Here is an screenshot of how burpsuite start on my desktop:
![image](https://github.com/r1vs3c/auto-bspwm/assets/103284308/733adb56-505e-405e-9213-f55d5600e3b4)

**Comment by r1vs3c** [comment]
By default, Burp Suite runs in floating window mode. To activate tile window mode, you need to press `Windows + T`.
