### ISSUE TITLE
Colours

### ISSUE THREAD

**Issue by H4des17** [r1vs3c/auto-bspwm#13]
Cuando creo un script al cual quiero añadir colores con un echo no se ejecutan bien los colores, están bien especificados pero al ejecutar el script solo muestra colores que pertenezcan a algún tono morado o azul, hay alguna forma de arreglarlo para que salgan bien los colores. Intuyo que es por la configuración del entorno ya que con el escritorio predeterminado de kali si muestra los colores que especifico

**Comment by r1vs3c** [comment]
Si, efectivamente, es por tema de configuración del entorno. Para definir la paleta de colores de la kitty, debes realizarlo en el archivo `~/.config/kitty/color.ini`. Si deseas puedes eliminar el archivo para tener los colores predeterminados.
