### ISSUE TITLE
I have this error

### ISSUE THREAD

**Issue by julian0830** [r1vs3c/auto-bspwm#15]
Note, selecting 'suckless-tools' instead of 'wmname'
Package firejail is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Error: Package 'firejail' has no installation candidate

[-] Failed to install some packages!

**Comment by johandavid77** [comment]
Yes My Lord, I got here too!!!

**Comment by johandavid77** [comment]
with https://github.com/netblue30/firejail/releases  i can solved the problem, test and tellme

**Comment by julian0830** [comment]
so how can i remove and reinstall bspwm?

**Comment by julian0830** [comment]
> with https://github.com/netblue30/firejail/releases i can solved the problem, test and tellme

bro I tried it but I still get the same error even after following the steps of the repository you sent

**Comment by johandavid77** [comment]
download the .deb file for your architecture and install with sudo dpkg -i name_of_package.deb

**Comment by r1vs3c** [comment]
> Note, selecting 'suckless-tools' instead of 'wmname' Package firejail is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source
> 
> Error: Package 'firejail' has no installation candidate
> 
> [-] Failed to install some packages!

Fixed
