### ISSUE TITLE
Tengo un problema con el teclado

### ISSUE THREAD

**Issue by RodBarrera** [r1vs3c/auto-bspwm#16]
Hola: 
Primero gracias por el aporte al compartir este entorno.
Tengo un problema a la hora de utilizar el teclado con la simbología, ya que uso teclado en español- latinoamerica y tengo todo cambiado los caracteres, trate de buscar el setting manager para buscar el layout pero no pude encontrarlo, se agradece cualquier consejo para poder solucionar este problema y poder utilizar el entorno.

Saludos!!

**Comment by Diego-h204** [comment]
Puedes arreglarlo escribiendo en la terminal "setxkbmap -layout es" (sin comillas).

**Comment by RodBarrera** [comment]
@Diego-h204  Funciono perfecto muchas gracias!! te pasaste!!

**Comment by Diego-h204** [comment]
> @Diego-h204 Funciono perfecto muchas gracias!! te pasaste!!
De nada!! Si el problema persiste intenta agregar ese comando al archivo .config/bspwm/bspwmrc, reinicia y ya deberia de haberse solucionado, te dejo el enlace que me ayudo:
https://es.stackoverflow.com/questions/578671/como-cambio-el-idioma-de-bspwm

**Comment by RodBarrera** [comment]
Gracias!! es un agrado que en este circulo  de la ciberseguridad siempre uno encuentra apoyo!!

**Comment by r1vs3c** [comment]
> Puedes arreglarlo escribiendo en la terminal "setxkbmap -layout es" (sin comillas).
>  Si el problema persiste intenta agregar ese comando al archivo .config/bspwm/bspwmrc, reinicia y ya deberia de haberse solucionado, te dejo el enlace que me ayudo:
https://es.stackoverflow.com/questions/578671/como-cambio-el-idioma-de-bspwm

Gracias por el aporte @Diego-h204 .
