### ISSUE TITLE
Kitty doesn't launch

### ISSUE THREAD

**Issue by y0moGh** [r1vs3c/auto-bspwm#3]
If I do either win + enter or I try to open it from the win + d menu, nothing happens. Kitty launches only if I execute the command 'kitty' from another terminal and only because I added export  "LIBGL_ALWAYS_SOFTWARE=true" to the .zshrc file (before doing that I got an error).

I also tried editing the keyboard hotkeys from settings, assigning win + enter to the kitty command but it didn't worked.

Thanks

**Comment by r1vs3c** [comment]
It's rare that this happens. Did you install it on a clean Kali Linux system? If not, I suggest uninstalling and reinstalling Kitty.

This is the key combination defined in the `sxhkdrc` file to execute Kitty:

```shell
super + Return
        /usr/bin/kitty
```

As you can see, the absolute path is `/usr/bin/kitty`. Make sure that yours is the same. If it's not, modify the sxhkdrc file with the correct path.

**Comment by y0moGh** [comment]
No, I didn't installed it on a clean Kali because I have everything there. Kitty's absolute path is /usr/bin/kitty and the `sxhkdrc ` file is correct. What should I do?

**Comment by r1vs3c** [comment]
I just remembered that I initially had the same issue on my virtual machine with VMware, and I resolved it by disabling the "**Accelerate 3D graphics**" option.

If you're using a virtual machine in VMware, you might want to give this a try.
