### ISSUE TITLE
terminal issue maybe

### ISSUE THREAD

**Issue by CarryLambo** [r1vs3c/auto-bspwm#4]
Hello, I love this project but I have a question, is it normal for the applications that I open with rofi to open with the terminal in this way? it seems strange to me
![2023-10-14_23-26](https://github.com/r1vs3c/auto-bspwm/assets/80961600/b696869f-a682-4c7b-9069-1fe669158a2e)

**Comment by r1vs3c** [comment]
It's not normal. It seems that terminal applications opened with `rofi` are using `qterminal` instead of `kitty`. I'm aware of the issue and will try to resolve it in the coming days.

**Comment by r1vs3c** [comment]
Hello again, to solve this issue, you need to add the following line:

```
terminal:                       "/usr/bin/kitty";
```

At the end of the "configuration" section within the file `~/.config/polybar/shapes/scripts/rofi/launcher.rasi`.

In any case, I will be updating the repository this week.

It's worth noting that in some programs, the terminal color configuration may be lost. A temporary solution to this is to reset the bspwm configuration by pressing <kbd>Windows</kbd> + <kbd>Alt</kbd> + <kbd>R</kbd>.
